version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: python -m flask run --host 0.0.0.0 --port 5000
    container_name: binday-server
    # depends_on:
    #   - postgres
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app/
    privileged: true
    devices:
      - '/dev:/dev'