version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: python -m flask run --host 0.0.0.0 --port 5000
    container_name: binday-server
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app/
    privileged: true
    devices:
      - '/dev:/dev'

  redis:
    container_name: redis
    image: redis
    hostname: redis

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A binday.workers.celery.worker worker -l info
    volumes:
      - ./:/usr/src/app/
    links:
      - redis
    depends_on:
      - redis
      - server
    privileged: true
    devices:
      - '/dev:/dev'
  
  scheduler:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    entrypoint: celery
    command: -A binday.workers.celery.worker beat --pidfile=/tmp/celerybeat.pid
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - worker