"""empty message

Revision ID: 7a998316135c
Revises: 
Create Date: 2020-05-19 19:56:07.471804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a998316135c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_day',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayindex'), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'FORTNIGHTLY', 'MONTHLY', name='collectionfrequency'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('my_bin',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('capacity', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('height', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('board_type', sa.Enum('UNO_R3', name='boardtype'), nullable=False),
    sa.Column('device_name', sa.String(length=32), nullable=False),
    sa.Column('sonar_id', sa.String(length=32), nullable=False),
    sa.Column('led_id', sa.String(length=32), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('bin_day_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bin_day_id'], ['bin_day.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_bin')
    op.drop_table('user')
    op.drop_table('bin_day')
    # ### end Alembic commands ###
